name: Discord Reminder

on:
  schedule:
    - cron: '*/45 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        run: |
          curl -X POST "https://discord.com/api/webhooks/1512789629097742437/UIFgw2ihKLr5pel4QbYrOSImigLLF1GJ9x0EytDHjS-oonw5CbsXUOYsU7i0AHz689RW" \
            -H "Content-Type: application/json" \
            -d '{"content": "PLAY!!!"}'
